# Show the active user stats for this week on Docracy
#
# radar - Show the loop

# quotes = [
#   "Behold, the instrument of your liberation!",
#   "It doesn't matter who we are... what matters is our plan.",
#   "Now's not the time for fear. That comes later.",
#   "Theatricality and deception, powerful agents for the uninitiated."
#   ]


module.exports = (robot) ->
  robot.respond /(bigboard|board|baneboard)( me)?/i, (msg) ->
  	bigBoardURL = process.env.BIGBOARD_URL
  	console.log("BIGBOARD_URL: " + bigBoardURL)
  	msg.http(bigBoardURL)
	  	.get() (err, res, body) ->
	  		if (msg.match[0].indexOf('bane') != -1)
	  			msg.send quotes[Math.floor(Math.random() * quotes.length)]+"\n" + body
	  		else
	  			msg.send body

quotes = [
  "Who we are does not matter. What matters is our plan.",
"It would be extremely painful.",
"For you.",
"Of course. Dr. Pavel refused our offer in favor of yours. We had to know what he told you about us.",
"He would not have told us.",
"Him, I need healthy. You present no such problem.",
"Crashing this plane...",
"(rising) With no survivors.",
"Friend. They expect one of us in the wreckage.",
"(nods) The fire rises.",
"Calm, Doctor. Now is not time for fear...",
"That comes later.",
"Why are you here?",
"I’m asking you.",
"And you brought him down here?",
"You panicked. And your weakness costs three lives.",
"Search him. Then I will kill you.",
"Then show me his body.",
"Give me your GPS.",
"Follow him.",
"Track him. Make sure both bodies will not be found. Then brick up the south tunnel.",
"Why else would you people be here?",
"Enter your password. Or I send these men to your home.",
"For now. How much longer does the program need?",
"Time to go mobile.",
"(O.S.) Speak of the devil...",
"...and he shall appear.",
"The plan is proceeding as expected.",
"(to Stryver) Leave us.",
"Do you feel in charge?",
"And that gives you power over me?",
"Your money and infrastructure have been important. Till now.",
"Gotham’s reckoning. Come to end the borrowed time you’ve all been living on...",
"I am necessary evil.",
"(O.S.) Not as serious as yours, I fear.",
"Let’s not stand on ceremony here, Mr. Wayne.",
"Peace has cost you strength. Victory has defeated you.",
"Theatricality and deception are powerful agents...to the uninitiated.",
"But we are initiated, aren’t we, Bruce? The League of Shadows. And you betrayed us...",
"Now I am the League of Shadows, here to fulfill R ̄a’s al Gh ̄ul’s destiny...",
"You fight like a younger man. Nothing held back. No reserves. Admirable. But mistaken.",
"You think darkness is your ally. But you merely adopted the dark. I was born in it. Formed by it...",
"I didn’t see the light until I was already a man. And by then it was nothing to me but blinding...",
"The shadows betray you, because they belong to me...",
"I will show you where I’ve made my home while preparing to bring justice. Then...I will break you.",
"Your precious armory. Gratefully accepted. We will need it.",
"I wondered which would break first - your spirit...",
"You don’t fear death. You welcome it. Your punishment is to be more severe.",
"Yes. But not of your body. Of your soul.",
"Home.",
"This meeting is called to order.",
"Chair and President. I also need one ordinary member - Mr. Fox, would you care to nominate?",
"Where you buried your resources. The bowels of Gotham.",
"Turn it on.",
"I only need one other board member. There are eight more waiting upstairs.",
"Do your work.",
"(to his men) Pull the core out of the reactor.",
"Five, by my calculations.",
"For the sake of your family, Dr. Pavel, I hope so.",
"Let the games begin.",
"Gotham, take control of your city...",
"This is the instrument of your liberation...",
"Identify yourself to the world.",
"Tell the world what this is.",
"And who can disarm this device?",
"Thank you, Doctor.",
"The bomb is armed, the bomb is mobile, the identity of the triggerman is a mystery. One of you holds the detonator - we come not as conquerors, but as liberators to return control of this city to the people. At the first sign of interference from the outside world or of people attempting to flee, this anonymous Gothamite, this unsung hero, will trigger the bomb. For now, martial law is in effect. Return to your homes, hold your families close, and wait. Tomorrow you claim what is rightfully yours.",
"Behind you stands a symbol of oppression. Blackgate Prison...",
"(O.S.) Where a thousand men have languished for years. Under the Dent Act. Under the name of this man -",
"Harvey Dent. Held up to you, and over you, as a shining example of justice and good...",
"But they supplied you a false idol. A straw man. To placate. To stop you tearing down this corrupt city...",
"(O.S.) ...and rebuilding it the way it should have been rebuilt generations ago...",
"Let me tell you the truth about Harvey Dent. In the words of Gotham’s Police Commissioner, James Gordon...",
"’The truth about Harvey Dent is simple in only one regard - it has been hidden for too long. After his devastating injuries, Harvey’s mind has recovered no better than his mutilated face. He was a broken, dangerous man, not the crusader for justice that I, James Gordon, have portrayed him to be for the last eight years. Harvey’s rage was indiscriminate. Psychopathic. He held my family at gunpoint, then fell to his death in the struggle over my son’s life. The Batman did not murder Harvey Dent - he saved",
"(cont’d) my boy. Then took the blame for Harvey’s appalling crimes, so that I could, to my shame, build a lie around this fallen idol.’",
"(V.O.) ’I praised the madman who tried to murder my own child.’",
"’The things we did in Harvey’s name brought desperately needed security to our streets... But I can no longer live with my lie. It is time to trust the people of Gotham with the truth, and it is time for me to resign.’",
"Do you accept the resignation of all the liars?! All the corrupt?!",
"We take Gotham from the corrupt. The rich. The oppressors of generations who’ve kept you down with the myth of opportunity. And we give it to you, the people. Gotham is yours - none shall interfere. Do as you please...",
"(cont’d) But start by storming Blackgate and freeing the oppressed... Step forward, those who would serve...",
"(V.O.) For an army will be raised...",
"(V.O.) The powerful will be ripped from their decadent nests...",
"(V.O.) ...and cast into the cold world the rest of us have known and endured...",
"(V.O.) Courts will be convened...",
"(V.O.) The spoils will be enjoyed...",
"(V.O.) Blood will be shed...",
"(V.O.) But the police will live, until they are ready to serve true justice...",
"(V.O.) This great city will endure...",
"(V.O.) Gotham will survive.",
"I’m on your schedule, Captain.",
"Give them over for judgement. (Indicates bodies.) Hang them where the world will see.",
"Bring her to me.",
"Impossible...",
"Open fire.",
"You came back. To die with your city.",
"Stay back. He is mine -",
"I broke you. How have you come back?",
"I never escaped - R ̄a’s al Gh ̄ul rescued me. That is why I must fulfill his plan. That is why I must avenge his murder.",
"Goodbye.",
"You’ll have to imagine the fire -"
]